project_id = "xbqiwuwemtaywedrjsgy"

[functions.send-program-confirmation]
verify_jwt = true

[functions.send-program-reminder]
verify_jwt = true

[functions.career-assistant]
verify_jwt = true

[functions.mentor-send-otp]
verify_jwt = false

[functions.mentor-verify-otp]
verify_jwt = false
